name: SimplePipeline

on:
  push:
    branches: [ main ]

jobs:
  LintAndDeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Install Netlify CLI
        run: npm install -g netlify-cli
      - name: Install Dependencies
        run: npm install
      - name: Run Linting
        run: npm run lint
      - name: Deploy
        run: npm run deploy:prod
        env:
          CI: true
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

